apiVersion: spec.keptn.sh/0.2.2
kind: "Shipyard"
metadata:
  name: "slo-demo"
spec:
  stages:
    - name: "production"
      sequences:
      - name: "getslo"
        tasks: 
        - name: "evaluation"
          properties:
            timeframe: "5m"
